[package]
name = "mna"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshot-rs = "0.1.5"
rdev = "0.5.3"
hyper = "1.3.1"
winit = "0.30.0"
image = "0.25.1"
actix-files = "0.6"
actix-web = "4"